import io.grafima.buildlogic.GenerateIcons
import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
}

kotlin {
    jvm()

    sourceSets {
        jvmMain.dependencies {
            implementation(project(":sample"))
            implementation(compose.desktop.currentOs)
        }
    }
}

compose.desktop {
    application {
        mainClass = "io.grafima.sample.desktop.MainKt"

        // `run` starts a bare JVM, so macOS names the menu bar and the Dock
        // after the main class until it is told otherwise. Packaged builds
        // take the name from nativeDistributions instead.
        jvmArgs += "-Dapple.awt.application.name=Grafima"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Grafima"
            // jpackage rejects anything but digits and dots, so a snapshot
            // packages under the release number it is heading for.
            packageVersion = providers.gradleProperty("VERSION_NAME").get().substringBefore('-')

            // Each installer wants its own format; the running app uses the PNG
            // in jvmMain/resources. All are generated by `generateIcons`.
            macOS { iconFile.set(project.file("icons/grafima.icns")) }
            windows { iconFile.set(project.file("icons/grafima.ico")) }
            linux { iconFile.set(project.file("src/jvmMain/resources/grafima-icon.png")) }
        }
    }
}

// The icons are generated from the same artwork iOS uses, and the results are
// committed. Run this when the logo changes; nothing runs it automatically.
tasks.register<GenerateIcons>("generateIcons") {
    group = "build"
    description = "Regenerates the desktop app icons from the iOS source artwork."
    source.set(
        rootProject.layout.projectDirectory
            .file("iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/grafima-icon-1024.png")
    )
    squareIcon.set(layout.projectDirectory.file("src/jvmMain/resources/grafima-icon.png"))
    macOsIcon.set(layout.projectDirectory.file("src/jvmMain/resources/grafima-icon-macos.png"))
    icns.set(layout.projectDirectory.file("icons/grafima.icns"))
    ico.set(layout.projectDirectory.file("icons/grafima.ico"))
}
